# Generated by Django 2.2.3 on 2019-08-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gonggo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('interest', models.CharField(choices=[('1', '디자인'), ('2', '번역'), ('3', '연구보조'), ('4', '프로그래밍')], max_length=2)),
                ('workDetail', models.TextField(max_length=100)),
                ('serviceAddr2', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('minMoney', models.CharField(max_length=100)),
                ('highMoney', models.CharField(max_length=100)),
                ('workTimeDetailContent', models.TextField(max_length=300)),
                ('manager1', models.CharField(max_length=100)),
                ('phonenum', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
