# Generated by Django 2.2.3 on 2019-08-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonggo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonggo',
            name='interest',
            field=models.CharField(choices=[('1', '디자인'), ('2', '번역'), ('3', '연구보조'), ('4', '프로그래밍')], default='a', max_length=2),
        ),
        migrations.AlterField(
            model_name='gonggo',
            name='salary',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
