# Generated by Django 2.2.3 on 2019-08-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonggo', '0002_auto_20190807_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonggo',
            name='email',
            field=models.CharField(default='a', max_length=30),
        ),
        migrations.AlterField(
            model_name='gonggo',
            name='highMoney',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='gonggo',
            name='manager1',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='gonggo',
            name='minMoney',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='gonggo',
            name='phonenum',
            field=models.CharField(default='a', max_length=20),
        ),
        migrations.AlterField(
            model_name='gonggo',
            name='serviceAddr2',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='gonggo',
            name='workDetail',
            field=models.TextField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='gonggo',
            name='workTimeDetailContent',
            field=models.TextField(default='a', max_length=300),
        ),
    ]
