# Generated by Django 2.2.3 on 2019-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonggo', '0003_auto_20190807_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonggo',
            name='person',
            field=models.IntegerField(default='0'),
        ),
    ]
