# Generated by Django 2.2.3 on 2019-08-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonggo', '0004_gonggo_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonggo',
            name='person',
            field=models.CharField(default='a', max_length=2),
        ),
    ]
