# Generated by Django 2.2.3 on 2019-07-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.TextField(blank=True, default='company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.TextField(blank=True, default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True, default='0'),
        ),
    ]
