# Generated by Django 2.2.3 on 2019-08-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_profile_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.CharField(choices=[('1', '번역'), ('2', '연구보조'), ('3', '프로그래밍'), ('4', '디자인')], max_length=2),
        ),
    ]
