# Generated by Django 2.2.3 on 2019-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_auto_20190807_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.CharField(choices=[('1', '디자인'), ('2', '번역'), ('3', '연구보조'), ('4', '프로그래밍')], max_length=2),
        ),
    ]
