# Generated by Django 2.2.3 on 2019-08-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_auto_20190810_0002'),
        ('myweb', '0005_auto_20190810_0047'),
    ]

    operations = [
    ]
